version:  '2'
services:
 
  config-server:
    image: config-server:v1.0.0
    build: config-server/
    container_name: config-container
    network_mode: host
    ports:
      - 8092:8092
    expose:
      - 8092
