version:  '2'
services:

  angular:
    image: frontend
    build: application-frontend
    ports:
      - 4200:4200
    expose:
      - 4200
    container_name: angular
  

  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=register
    volumes:
      - '/data/mysql_data:/var/lib/mysql'
    network_mode: "host"
    hostname: localhost

   

  mongodb:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"


  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_dbms_secuity_procedures_unrestricted=apoc.*
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - '/neo4j/graph:/data'

#ZOOKEEPER MESSAFEBROKER
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
    - "2181:2181"
   network_mode: "host"
   hostname: localhost
   restart: always

#KAFKA MESSAGING
  kafka:
   image: wurstmeister/kafka
   ports:
    - "9092:9092"
   environment:
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_LISTENERS: PLAINTEXT://localhost:9092
    KAFKA_ZOOKEEPER_CONNECT: localhost:2181
   network_mode: "host"
   hostname: localhost
   depends_on:
    - zookeeper  
   restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - '/data/redis:/data'
    restart: always

  show-service:

    depends_on:
      - mongodb
      - kafka

  search-service:

    depends_on:
      - mongodb
      - kafka


  distributor:
     
    depends_on:
#      - eureka
#      - config-server
      - mongodb

  user-registration:

    depends_on:
#      - eureka
#      - config-server
      - mongodb
      - kafka

  user-authentication:
   
    depends_on:
#      - eureka
#      - config-server
      - mysql
      - kafka

  producer-registration:

    depends_on:
#      - eureka
#      - config-server
      - mongodb

  recommendation:

    depends_on:
#      - eureka
#      - config-server
      - neo4j
      - mongodb
      - kafka

  booking-service:

    depends_on:
      - mongodb
      - kafka
      - redis

  rsvp-service:

    depends_on:
      - mongodb
      - kafka

  email-service:

    depends_on:
      - kafka

  scheduler:

    depends_on:
#     - eureka
#     - config-server
      - kafka

  payment:

    depends_on: 
      - mongodb
    
  zuul:

    depends_on:
      - recommendation
      - producer-registration
      - user-authentication
      - user-registration
      - distributor
      - show-service
      - booking-service
      - rsvp-service
      - email-service
      - scheduler
      - payment
      - search-service
       
  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8089:80"
    depends_on:
      - recommendation
      - producer-registration
      - user-authentication
      - user-registration
      - distributor
      - show-service
      - booking-service
      - rsvp-service
      - email-service
      - scheduler
      - payment
      - search-service

