version: '2'
services:

  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=register
    volumes:
      - /opt/datasql:/var/lib/mysql
    network_mode: "host"
    hostname: localhost
    #    restart: always

