version: '2'
services:
  search-service:
    image: search-service
    build: search-service/
    container_name: search-service
    network_mode: host
    ports:
      - 8081:8081
    expose:
      - 8081
    restart: always


