FROM openjdk:8-jdk
WORKDIR usr/app
ADD ./target/producer-registration-service-0.0.1-SNAPSHOT.jar /usr/app/producer-registration-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","producer-registration-service-0.0.1-SNAPSHOT.jar"]
